# Generated by Django 5.0.1 on 2024-01-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
    ]
