# Generated by Django 5.0.1 on 2024-01-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={},
        ),
    ]
