# Generated by Django 5.0.1 on 2024-01-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_prof', models.CharField(max_length=200)),
            ],
        ),
    ]
