# Generated by Django 5.0.1 on 2024-01-19 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ma_de_tai', models.CharField(max_length=10)),
                ('Ten_de_tai', models.CharField(max_length=200)),
                ('Loai_san_pham', models.CharField(max_length=200)),
                ('Ngay_bat_dau', models.DateField()),
                ('Ngay_ket_thuc', models.DateField()),
                ('Trang_thai', models.CharField(choices=[('đã duyệt', 'Đã duyệt'), ('chưa duyệt', 'Chưa duyệt')], default='chưa duyệt', max_length=20)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
            ],
        ),
    ]
