# Generated by Django 5.0.1 on 2024-01-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Trang_thai',
            field=models.CharField(choices=[('đã duyệt', 'Đã duyệt'), ('yêu cầu sửa đổi', 'Yêu cầu sửa đổi'), ('đã hủy', 'Đã hủy'), ('đang thực hiện', 'Đang thực hiện'), ('hoàn tất nghiệm thu', 'Hoàn tất nghiệm thu')], default='yêu cầu sửa đổi', max_length=20),
        ),
    ]
