# Generated by Django 5.0.1 on 2024-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tap_chi_dien_tu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoi_nghi_hoi_thao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ten_hoi_thao', models.CharField(max_length=10)),
                ('Muc_dich', models.CharField(max_length=1000)),
                ('Yeu_cau', models.CharField(max_length=1000)),
                ('Thanh_phan_tham_du', models.CharField(max_length=800)),
                ('So_luong_tham_du', models.CharField(max_length=800)),
                ('Noi_dung_chi_tiet', models.CharField(max_length=10000)),
                ('Ngay_du_kien', models.DateField()),
                ('Ngay_ket_thuc', models.DateField()),
                ('Dia_diem', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
