# Generated by Django 5.0.1 on 2024-01-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hoi_nghi_hoi_thao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(max_length=200, verbose_name='Lĩnh vực'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Dia_diem',
            field=models.CharField(max_length=800, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Muc_dich',
            field=models.CharField(max_length=1000, verbose_name='Mục đích'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Ngay_du_kien',
            field=models.DateField(verbose_name='Ngày dự kiến'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Ngay_ket_thuc',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Noi_dung_chi_tiet',
            field=models.CharField(max_length=10000, verbose_name='Nội dung chi tiết'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='So_luong_tham_du',
            field=models.CharField(max_length=800, verbose_name='Số lượng tham dự'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Ten_hoi_thao',
            field=models.CharField(max_length=10, verbose_name='Tên hội thảo'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Thanh_phan_tham_du',
            field=models.CharField(max_length=800, verbose_name='Thành phần tham dự'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='Yeu_cau',
            field=models.CharField(max_length=1000, verbose_name='Yêu cầu'),
        ),
        migrations.AlterField(
            model_name='hoi_nghi_hoi_thao',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='File đính kèm'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=200, verbose_name='Cấp độ đề tài'),
        ),
        migrations.AlterField(
            model_name='project_profile',
            name='pro_prof',
            field=models.CharField(max_length=200, verbose_name='Hồ sơ đề tài'),
        ),
        migrations.AlterField(
            model_name='tap_chi_dien_tu',
            name='Doi_tuong',
            field=models.CharField(choices=[('sinh viên', 'Sinh viên'), ('giảng viên', 'Giảng viên')], default='sinh viên', max_length=20, verbose_name='Đối tượng'),
        ),
        migrations.AlterField(
            model_name='tap_chi_dien_tu',
            name='Ghi_chu',
            field=models.CharField(max_length=800, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='tap_chi_dien_tu',
            name='Giang_vien_huong_dan',
            field=models.CharField(max_length=800, verbose_name='Giảng viên hướng dẫn'),
        ),
        migrations.AlterField(
            model_name='tap_chi_dien_tu',
            name='Ho_ten',
            field=models.CharField(max_length=10, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='tap_chi_dien_tu',
            name='Ngay_sinh',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tap_chi_dien_tu',
            name='Ten_y_tuong',
            field=models.CharField(max_length=800, verbose_name='Tên ý tưởng'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=200, verbose_name='Năm học'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
