# Generated by Django 5.0.1 on 2024-01-23 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_field_field_alter_hoi_nghi_hoi_thao_dia_diem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ma_de_tai', models.CharField(max_length=10, verbose_name='Mã đề tài')),
                ('Ten_de_tai', models.CharField(max_length=200, verbose_name='Tên đề tài')),
                ('Chu_nhiem', models.CharField(max_length=800, verbose_name='Chủ nhiệm')),
                ('Thanh_vien', models.CharField(max_length=800, verbose_name='Thành viên')),
                ('Kinh_phi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Loai_san_pham', models.CharField(max_length=200, verbose_name='Loại sản phẩm')),
                ('Ngay_bat_dau', models.DateField(verbose_name='Ngày bắt đầu')),
                ('Ngay_ket_thuc', models.DateField(verbose_name='Ngày kết thúc')),
                ('Trang_thai', models.CharField(choices=[('đã duyệt', 'Đã duyệt'), ('yêu cầu sửa đổi', 'Yêu cầu sửa đổi'), ('đã hủy', 'Đã hủy'), ('đang thực hiện', 'Đang thực hiện'), ('hoàn tất nghiệm thu', 'Hoàn tất nghiệm thu')], default='yêu cầu sửa đổi', max_length=20, verbose_name='Trạng thái')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.field', verbose_name='Lĩnh vực')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level', verbose_name='Cấp độ đề tài')),
            ],
        ),
    ]
